CREATE TABLE IF NOT EXISTS `rcf_db`.`USER` (
  `USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(50) NOT NULL,
  `PWD` VARCHAR(32) NULL,
  `ROLE_ADMIN` TINYINT(1) NOT NULL,
  `STATUS` TINYINT(1) NOT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `rcf_db`.`CONTENT` (
  `CONTENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(11) NOT NULL,
  `COMPONENT_ID` VARCHAR(100) NOT NULL,
  `URL` VARCHAR(300) NOT NULL,
  `TITLE` VARCHAR(250) NOT NULL,
  `CONTENT` LONGTEXT NOT NULL,
  `CREATION_DT` DATETIME NOT NULL,
  `LAST_UPDATE_DT` DATETIME NULL,
  `STATUS` TINYINT(1) NOT NULL,
  PRIMARY KEY (`CONTENT_ID`, `USER_ID`),
  INDEX `fk_CONTENT_USER1_idx` (`USER_ID` ASC),
  CONSTRAINT `fk_CONTENT_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `rcf_db`.`USER` (`USER_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `rcf_db`.`PARAMETER` (
  `PARAMETER_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `KEY` VARCHAR(100) NOT NULL,
  `VALUE` LONGTEXT NOT NULL,
  PRIMARY KEY (`PARAMETER_ID`))
ENGINE = InnoDB
